apiVersion: v2  #previosuly v1 now upgraded to v2 
name: nginx #Chart name
version: 1.0.1 # chart version 
description: upgrading to stable-perl version #chart description 
appVersion: latest # this is application version